### ISSUE TITLE
get npm ERR! Cannot read properties of undefined (reading 'spec') error

### ISSUE THREAD

**Issue by lewiss444** [mvasin/react-div-100vh#70]
Tried to install on a Gatsby V3 website via npm, got 238 line in the log, here they are:

220 timing auditReport:init Completed in 33087ms
221 timing reify:audit Completed in 34348ms
222 timing reifyNode:node_modules/undefined Completed in 125553ms
223 timing reify:unpack Completed in 125553ms
224 timing reify:unretire Completed in 1ms
225 timing build:queue Completed in 35ms
226 timing build:deps Completed in 35ms
227 timing build Completed in 35ms
228 timing reify:build Completed in 35ms
229 timing reify:trash Completed in 0ms
230 timing command:install Completed in 132733ms
231 verbose stack TypeError: Cannot read properties of undefined (reading 'spec')
231 verbose stack     at Arborist.[saveIdealTree] (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:1086:44)
231 verbose stack     at Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:150:31)
231 verbose stack     at async Install.install (/opt/homebrew/lib/node_modules/npm/lib/install.js:150:5)
232 verbose cwd /Applications/MAMP/htdocs/react
233 verbose Darwin 20.6.0
234 verbose argv "/opt/homebrew/Cellar/node/16.9.1/bin/node" "/opt/homebrew/bin/npm" "install" "react-div-100vh" "https://github.com/mvasin/react-div-100vh.git"
235 verbose node v16.9.1
236 verbose npm  v7.21.1
237 error Cannot read properties of undefined (reading 'spec')
238 verbose exit 1

**Comment by mvasin** [comment]
Hi @lewiss444, thanks for sharing. Will have a look when time permits. If someone can tackle it in the meantime - you are very welcome.
